/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package transaksi;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.*;
import javax.swing.*;
import java.text.SimpleDateFormat;
import tampilanMenu.loginSesi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.HashMap;
import koneksi.koneksi;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ALKHOIR
 */

public class pengembalian_Barang extends javax.swing.JPanel {
    final private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    private String hakAkses;
    /**
     * Creates new form pengembalian_Barang
     */
    public pengembalian_Barang() {
        initComponents();
        generateIdPengembalian();
        dataTable();
        
        String loginIdKaryawan = loginSesi.getIdKaryawan();
        idKaryawan.setText(loginIdKaryawan);
        String loginNamaKaryawan = loginSesi.getNamaKaryawan();
        namaKaryawan.setText(loginNamaKaryawan);
        hakAkses = loginSesi.getHakAkses();
        
        String idBaru = generateIdPengembalian();
        idPengembalian.setText(idBaru);
    }
    
    private void dataTable(){
        String[] kolom = {"id Pengembalian", "id_transaksi", "id_barang", "nama_barang", "Jumlah_barang", "tanggal"};
        tabmode = new DefaultTableModel(null, kolom);
        tablePengembalian.setModel(tabmode);
    }
    
    private String generateIdPengembalian() {
            String idBaru = "PB001";
        try {
            String sql = "SELECT MAX(RIGHT(id_transaksi, 3)) AS nomor FROM dataTransaksi WHERE id_transaksi LIKE 'PB%'";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                int nomor = rs.getInt("nomor") + 1;
                idBaru = String.format("PB%03d", nomor);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal generate ID Pengembalian: " + e.getMessage());
        }
        return idBaru;
    }
    
    private void kosong() {
        idBarang.setSelectedIndex(0);
        namaBarang.setText("");
        jumlah.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        bCetak = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bKembalikan = new javax.swing.JButton();
        bCari = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePengembalian = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaBarang = new javax.swing.JTextField();
        idPengembalian = new javax.swing.JTextField();
        idKaryawan = new javax.swing.JTextField();
        idBarang = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        jumlah = new javax.swing.JTextField();
        namaKaryawan = new javax.swing.JTextField();
        idPeminjaman = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1040, 600));
        setMinimumSize(new java.awt.Dimension(1040, 600));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("DATA TRANSAKSI > PENGEMBALIAN BARANG");

        bCetak.setBackground(new java.awt.Color(41, 76, 55));
        bCetak.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        bCetak.setForeground(new java.awt.Color(255, 255, 255));
        bCetak.setText("Cetak");
        bCetak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCetak.setMaximumSize(new java.awt.Dimension(200, 40));
        bCetak.setMinimumSize(new java.awt.Dimension(200, 40));
        bCetak.setPreferredSize(new java.awt.Dimension(200, 40));
        bCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCetakActionPerformed(evt);
            }
        });

        bKeluar.setBackground(new java.awt.Color(41, 76, 55));
        bKeluar.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        bKeluar.setForeground(new java.awt.Color(255, 255, 255));
        bKeluar.setText("Bersihkan");
        bKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bKeluar.setMaximumSize(new java.awt.Dimension(200, 40));
        bKeluar.setMinimumSize(new java.awt.Dimension(200, 40));
        bKeluar.setPreferredSize(new java.awt.Dimension(200, 40));
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        bSimpan.setBackground(new java.awt.Color(41, 76, 55));
        bSimpan.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        bSimpan.setForeground(new java.awt.Color(255, 255, 255));
        bSimpan.setText("Simpan");
        bSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSimpan.setMaximumSize(new java.awt.Dimension(200, 40));
        bSimpan.setMinimumSize(new java.awt.Dimension(200, 40));
        bSimpan.setPreferredSize(new java.awt.Dimension(200, 40));
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bKembalikan.setBackground(new java.awt.Color(41, 76, 55));
        bKembalikan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bKembalikan.setForeground(new java.awt.Color(255, 255, 255));
        bKembalikan.setText("Kembalikan");
        bKembalikan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bKembalikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKembalikanActionPerformed(evt);
            }
        });

        bCari.setBackground(new java.awt.Color(41, 76, 55));
        bCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bCari.setForeground(new java.awt.Color(255, 255, 255));
        bCari.setText("Cari");
        bCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCariActionPerformed(evt);
            }
        });

        jLabel4.setText("ID Pengembalian");

        jLabel6.setText("ID Barang");

        tablePengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pengembalian", "ID Barang", "Nama Barang", "Jumlah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePengembalian);

        jLabel7.setText("Nama Barang");

        jLabel2.setText("ID Karyawan");

        jLabel5.setText("ID Peminjaman");

        namaBarang.setMaximumSize(new java.awt.Dimension(250, 25));
        namaBarang.setMinimumSize(new java.awt.Dimension(250, 25));
        namaBarang.setPreferredSize(new java.awt.Dimension(250, 25));

        idPengembalian.setMaximumSize(new java.awt.Dimension(250, 25));
        idPengembalian.setMinimumSize(new java.awt.Dimension(250, 25));
        idPengembalian.setPreferredSize(new java.awt.Dimension(250, 25));

        idKaryawan.setEditable(false);
        idKaryawan.setFocusable(false);
        idKaryawan.setMaximumSize(new java.awt.Dimension(250, 25));
        idKaryawan.setMinimumSize(new java.awt.Dimension(250, 25));
        idKaryawan.setPreferredSize(new java.awt.Dimension(250, 25));

        idBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        idBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        idBarang.setMaximumSize(new java.awt.Dimension(250, 25));
        idBarang.setMinimumSize(new java.awt.Dimension(250, 25));
        idBarang.setPreferredSize(new java.awt.Dimension(250, 25));
        idBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idBarangMouseClicked(evt);
            }
        });

        jLabel8.setText("Jumlah");

        jLabel9.setText("Tanggal");

        jLabel3.setText("Nama Karyawan");

        tanggal.setMaximumSize(new java.awt.Dimension(250, 25));
        tanggal.setMinimumSize(new java.awt.Dimension(250, 25));
        tanggal.setPreferredSize(new java.awt.Dimension(250, 25));

        jumlah.setMaximumSize(new java.awt.Dimension(250, 25));
        jumlah.setMinimumSize(new java.awt.Dimension(250, 25));
        jumlah.setPreferredSize(new java.awt.Dimension(250, 25));

        namaKaryawan.setEditable(false);
        namaKaryawan.setFocusable(false);
        namaKaryawan.setMaximumSize(new java.awt.Dimension(250, 25));
        namaKaryawan.setMinimumSize(new java.awt.Dimension(250, 25));
        namaKaryawan.setPreferredSize(new java.awt.Dimension(250, 25));

        idPeminjaman.setMaximumSize(new java.awt.Dimension(250, 25));
        idPeminjaman.setMinimumSize(new java.awt.Dimension(250, 25));
        idPeminjaman.setPreferredSize(new java.awt.Dimension(250, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(idPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(idPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bCari))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(idBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(bKembalikan, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(bCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(bKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCari))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(bKembalikan, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(44, 44, 44)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(99, 99, 99)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCetakActionPerformed
        try {
            String reportPath = System.getProperty("user.dir") + File.separator + "src" + File.separator + "report" + File.separator + "LaporanPengembalian.jasper";
            HashMap<String, Object> parameters = new HashMap<>();
            JasperPrint print = JasperFillManager.fillReport(reportPath,parameters,conn);
            JasperViewer viewer = new JasperViewer(print,false);
            viewer.setVisible(true);
        } catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal menampilkan laporan:\n" + e.getMessage());
        }
        
        DefaultTableModel model = (DefaultTableModel) tablePengembalian.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_bCetakActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        kosong();
    }//GEN-LAST:event_bKeluarActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        String idPengembalian = generateIdPengembalian();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalKembalian = sdf.format(tanggal.getDate());

        String sql = "INSERT INTO datatransaksi (id_transaksi, id_karyawan, nama_karyawan, tanggal) VALUES (?, ?, ?, ?)";
        
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, idPengembalian);
            ps.setString(2, idKaryawan.getText());
            ps.setString(3, namaKaryawan.getText());
            ps.setString(4, tanggalKembalian);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data pengembalian berhasil disimpan");
            kosong();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data pengembalian: " + ex.getMessage());
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bKembalikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKembalikanActionPerformed
        String idPengembalian = generateIdPengembalian();
        String idPeminjaman1 = idPeminjaman.getText();
        String idBarang1 = idBarang.getSelectedItem().toString();
        String namaBarang = this.namaBarang.getText();
        String jumlahBarang = jumlah.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalKembalian = sdf.format(tanggal.getDate());
        
        tabmode = (DefaultTableModel) tablePengembalian.getModel();

        try {
            String sqlInsert = "INSERT INTO datapengembalian (id_pengembalian, id_transaksi, id_barang, nama_barang, jumlah_kembali, tanggal_kembali) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(sqlInsert);
            ps.setString(1, idPengembalian);
            ps.setString(2, idPeminjaman1);
            ps.setString(3, idBarang1);
            ps.setString(4, namaBarang);
            ps.setString(5, jumlahBarang);
            ps.setString(6, tanggalKembalian);
            ps.executeUpdate();

            String sqlUpdateStok = "UPDATE stokbarang SET stok_barang = stok_barang + ? WHERE id_barang = ?";
            PreparedStatement psUpdate = conn.prepareStatement(sqlUpdateStok);
            psUpdate.setInt(1, Integer.parseInt(jumlahBarang));
            psUpdate.setString(2, idBarang1);
            psUpdate.executeUpdate();

            String[] data = {idPengembalian, idPeminjaman1, idBarang1, namaBarang, jumlahBarang, tanggalKembalian};
            tabmode.insertRow(0, data);

            kosong();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal mengembalikan barang: " + e.getMessage());
        }
    }//GEN-LAST:event_bKembalikanActionPerformed

    private void bCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCariActionPerformed
        /* Flow untuk button ini 
        1. User memasukkan idPeminjaman (
        2. Sistem akan mendeteksi apakah ada peminjaman atau tidak 
        3. Jika ada sistem akan memberikan idBarang yang dipinjam 
        4. Jika barang sudah ada yang dikembalikan maka sistem akan memberikan barang yang belum kembalikan 
        */
        
        String idPeminjaman1 = idPeminjaman.getText().trim();
        
        try {
            if (idPeminjaman1.isEmpty()) { 
                JOptionPane.showMessageDialog(null, "Masukkan ID Peminjaman terlebih dahulu!");
                return; 
            }   
        
            /*
                String sql = """ 
                     SELECT 
                         dti.id_transaksi,
                         dti.id_barang,
                         dti.nama_barang,
                         dti.jumlah_barang AS total_pinjam,
                         IFNULL(SUM(dp.jumlah_kembali), 0) AS total_kembali,
                         (dti.jumlah_barang - IFNULL(SUM(dp.jumlah_kembali), 0)) AS sisa_belum_kembali
                     FROM datatransaksiinfo dti
                     LEFT JOIN datapengembalian dp
                         ON dti.id_transaksi COLLATE utf8mb4_general_ci = dp.id_transaksi COLLATE utf8mb4_general_ci
                         AND dti.id_barang COLLATE utf8mb4_general_ci = dp.id_barang COLLATE utf8mb4_general_ci
                     WHERE dti.id_transaksi COLLATE utf8mb4_general_ci = ?
                     GROUP BY dti.id_transaksi, dti.id_barang, dti.nama_barang, dti.jumlah_barang
                     HAVING sisa_belum_kembali > 0;
                """;
            */
            
            String sql = """ 
                    SELECT 
                        dti.id_transaksi,
                        dti.id_barang,
                        dti.nama_barang,
                        dti.jumlah_barang AS total_pinjam,
                        IFNULL(SUM(dp.jumlah_kembali), 0) AS total_kembali,
                        (dti.jumlah_barang - IFNULL(SUM(dp.jumlah_kembali), 0)) AS sisa
                    FROM datatransaksiinfo dti
                    LEFT JOIN datapengembalian dp 
                        ON dti.id_transaksi COLLATE utf8mb4_general_ci = dp.id_transaksi COLLATE utf8mb4_general_ci
                        AND dti.id_barang COLLATE utf8mb4_general_ci = dp.id_barang COLLATE utf8mb4_general_ci
                    WHERE dti.id_transaksi COLLATE utf8mb4_general_ci = ?
                    GROUP BY 
                        dti.id_transaksi, 
                        dti.id_barang, 
                        dti.nama_barang, 
                        dti.jumlah_barang
                    HAVING sisa > 0;

                    """;
        
        PreparedStatement ps = conn.prepareStatement(sql); 
        ps.setString(1, idPeminjaman1);
        ResultSet rs = ps.executeQuery();
        
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("Pilihan barang");
        
        boolean adaData = false;
        while (rs.next()) { 
            adaData = true; 
            model.addElement(rs.getString("id_barang"));
        }
        
        if (!adaData) { 
            JOptionPane.showMessageDialog(null, "ID peminjaman tidak ditemukan!");
            idBarang.setModel(new DefaultComboBoxModel<>(new String[]{"Pilihan barang"})); 
            namaBarang.setText(""); return; 
        }
        
        idBarang.setModel(model); 

        for (ActionListener al : idBarang.getActionListeners()) { 
            idBarang.removeActionListener(al); 
        }
        
        idBarang.addActionListener(e -> {
            try { 
                String selectedId = idBarang.getSelectedItem().toString();
                if (selectedId.equals("Pilihan barang")) { 
                    namaBarang.setText("");
                return; 
                }
                
                String query = """ 
                               SELECT nama_barang 
                               FROM databarang 
                               WHERE id_barang COLLATE utf8mb4_general_ci = ? 
                """;
                
                PreparedStatement ps2 = conn.prepareStatement(query);
                ps2.setString(1, selectedId);
                ResultSet rs2 = ps2.executeQuery();
                
                if (rs2.next()) {
                    namaBarang.setText(rs2.getString("nama_barang"));
                } else { 
                    namaBarang.setText("");
                } 
                
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Gagal mengambil data barang: " + ex.getMessage()); 
                } 
        });
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan: " + ex.getMessage());
        }
}//GEN-LAST:event_bCariActionPerformed


    private void idBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idBarangMouseClicked
        //OPTION
    }//GEN-LAST:event_idBarangMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCari;
    private javax.swing.JButton bCetak;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bKembalikan;
    private javax.swing.JButton bSimpan;
    private javax.swing.JComboBox<String> idBarang;
    private javax.swing.JTextField idKaryawan;
    private javax.swing.JTextField idPeminjaman;
    private javax.swing.JTextField idPengembalian;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField namaBarang;
    private javax.swing.JTextField namaKaryawan;
    private javax.swing.JTable tablePengembalian;
    private com.toedter.calendar.JDateChooser tanggal;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
