/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package reportMenu;

/**
 *
 * @author ALKHOIR
 */
public class menu_Report extends javax.swing.JPanel {

    /**
     * Creates new form menu_Report
     */
    public menu_Report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel2 = new keeptoo.KGradientPanel();
        pn_acc = new javax.swing.JPanel();
        pn_liacc = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        btn_acc = new javax.swing.JLabel();
        pn_acc1 = new javax.swing.JPanel();
        pn_liacc1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_acc1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(910, 600));
        setLayout(new java.awt.BorderLayout());

        kGradientPanel2.setkEndColor(new java.awt.Color(41, 76, 55));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 153, 153));

        pn_acc.setBackground(new java.awt.Color(255, 255, 255));
        pn_acc.setPreferredSize(new java.awt.Dimension(210, 37));

        pn_liacc.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_liaccLayout = new javax.swing.GroupLayout(pn_liacc);
        pn_liacc.setLayout(pn_liaccLayout);
        pn_liaccLayout.setHorizontalGroup(
            pn_liaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_liaccLayout.setVerticalGroup(
            pn_liaccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        jLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMouseEntered(evt);
            }
        });

        btn_acc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_acc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_acc.setText("REPORT BY DATE");
        btn_acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_accMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_accMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_accMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_accLayout = new javax.swing.GroupLayout(pn_acc);
        pn_acc.setLayout(pn_accLayout);
        pn_accLayout.setHorizontalGroup(
            pn_accLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_accLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_acc, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pn_accLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_accLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_liacc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(244, Short.MAX_VALUE)))
        );
        pn_accLayout.setVerticalGroup(
            pn_accLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_accLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_accLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_acc, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pn_accLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_accLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_liacc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pn_acc1.setBackground(new java.awt.Color(255, 255, 255));
        pn_acc1.setPreferredSize(new java.awt.Dimension(210, 37));

        pn_liacc1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_liacc1Layout = new javax.swing.GroupLayout(pn_liacc1);
        pn_liacc1.setLayout(pn_liacc1Layout);
        pn_liacc1Layout.setHorizontalGroup(
            pn_liacc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_liacc1Layout.setVerticalGroup(
            pn_liacc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        btn_acc1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_acc1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_acc1.setText("REPORT BY DIVISION");
        btn_acc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_acc1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_acc1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_acc1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_acc1Layout = new javax.swing.GroupLayout(pn_acc1);
        pn_acc1.setLayout(pn_acc1Layout);
        pn_acc1Layout.setHorizontalGroup(
            pn_acc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_acc1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_acc1)
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(pn_acc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_acc1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_liacc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(244, Short.MAX_VALUE)))
        );
        pn_acc1Layout.setVerticalGroup(
            pn_acc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_acc1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_acc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_acc1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pn_acc1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_acc1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_liacc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_acc1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_acc, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(pn_acc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(pn_acc1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        add(kGradientPanel2, java.awt.BorderLayout.LINE_START);

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(pn_utama, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pn_utama, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMouseEntered

    }//GEN-LAST:event_jLabelMouseEntered

    private void btn_accMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_accMouseClicked

    }//GEN-LAST:event_btn_accMouseClicked

    private void btn_accMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_accMouseEntered

    }//GEN-LAST:event_btn_accMouseEntered

    private void btn_accMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_accMouseExited

    }//GEN-LAST:event_btn_accMouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void btn_acc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_acc1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_acc1MouseClicked

    private void btn_acc1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_acc1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_acc1MouseEntered

    private void btn_acc1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_acc1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_acc1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_acc;
    private javax.swing.JLabel btn_acc1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JPanel pn_acc;
    private javax.swing.JPanel pn_acc1;
    private javax.swing.JPanel pn_liacc;
    private javax.swing.JPanel pn_liacc1;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
