/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilanMenu;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author ALKHOIR
 */

public class menu_inventaris extends javax.swing.JFrame {
    final private JTextField pathFoto;
    
    /**
     * Creates new form cobamenu
     */
    public menu_inventaris() {
        initComponents();
        
        setTitle("Inventaris Perkantoran");
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/logof.png"));
        setIconImage(icon.getImage());
        
        pathFoto = new JTextField();
        pathFoto.setVisible(false);
        add(pathFoto);
        
        String loginIdKaryawan = tampilanMenu.loginSesi.getIdKaryawan();
        String fileName = loginIdKaryawan + ".jpg";
        String destDir = System.getProperty("user.dir") + File.separator + "src" + File.separator + "imagesKaryawan" + File.separator;
        String fullPath = destDir + fileName;
            
        pathFoto.setText(fullPath);

        try {
            BufferedImage bi = ImageIO.read(new File(fullPath));
            Image img = bi.getScaledInstance(165, 191, Image.SCALE_SMOOTH); 
            ImageIcon icons = new ImageIcon(img);
            foto.setIcon(icons);
        } catch (IOException e) {
            foto.setIcon(null);
            System.out.println("Gagal menampilkan gambar: " + e.getMessage());
        }
        
        String loginNamaKaryawan = tampilanMenu.loginSesi.getNamaKaryawan();
        namaKaryawan.setText(loginNamaKaryawan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        namaKaryawan = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pn_itemB = new javax.swing.JPanel();
        pn_liitemB = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btn_itemB = new javax.swing.JLabel();
        pn_itemIn = new javax.swing.JPanel();
        pn_liitemIn = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btn_itemIn = new javax.swing.JLabel();
        pn_itemO = new javax.swing.JPanel();
        pn_liitemO = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btn_itemO = new javax.swing.JLabel();
        pn_itemRe = new javax.swing.JPanel();
        pn_liitemRe = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btn_itemRe = new javax.swing.JLabel();
        pn_itemReq = new javax.swing.JPanel();
        pn_liitemReq = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btn_itemReq = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pn_report = new javax.swing.JPanel();
        pn_lireport = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btn_report = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jPanel4 = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1170, 710));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(250, 700));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(250, 700));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconBaru/exit.png"))); // NOI18N
        jLabel22.setText("Logout");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        namaKaryawan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namaKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaKaryawan.setText("NAMA KARYAWAN");

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("TRANSACTION DATA");

        pn_itemB.setBackground(new java.awt.Color(255, 255, 255));
        pn_itemB.setPreferredSize(new java.awt.Dimension(222, 37));

        pn_liitemB.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_liitemBLayout = new javax.swing.GroupLayout(pn_liitemB);
        pn_liitemB.setLayout(pn_liitemBLayout);
        pn_liitemBLayout.setHorizontalGroup(
            pn_liitemBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_liitemBLayout.setVerticalGroup(
            pn_liitemBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconBaru/borrowing.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
        });

        btn_itemB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_itemB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_itemB.setText("Item Borrowing");
        btn_itemB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_itemBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_itemBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_itemBMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_itemBLayout = new javax.swing.GroupLayout(pn_itemB);
        pn_itemB.setLayout(pn_itemBLayout);
        pn_itemBLayout.setHorizontalGroup(
            pn_itemBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_itemBLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_itemB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_itemBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_itemBLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_liitemB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(194, Short.MAX_VALUE)))
        );
        pn_itemBLayout.setVerticalGroup(
            pn_itemBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_itemBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_itemBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_itemB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pn_itemBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_itemBLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_liitemB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_itemIn.setBackground(new java.awt.Color(255, 255, 255));
        pn_itemIn.setPreferredSize(new java.awt.Dimension(222, 37));

        pn_liitemIn.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_liitemInLayout = new javax.swing.GroupLayout(pn_liitemIn);
        pn_liitemIn.setLayout(pn_liitemInLayout);
        pn_liitemInLayout.setHorizontalGroup(
            pn_liitemInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_liitemInLayout.setVerticalGroup(
            pn_liitemInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconBaru/incoming.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
        });

        btn_itemIn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_itemIn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_itemIn.setText("Item Incoming");
        btn_itemIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_itemInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_itemInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_itemInMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_itemInLayout = new javax.swing.GroupLayout(pn_itemIn);
        pn_itemIn.setLayout(pn_itemInLayout);
        pn_itemInLayout.setHorizontalGroup(
            pn_itemInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_itemInLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_itemIn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_itemInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_itemInLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_liitemIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(194, Short.MAX_VALUE)))
        );
        pn_itemInLayout.setVerticalGroup(
            pn_itemInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_itemInLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_itemInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_itemIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pn_itemInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_itemInLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_liitemIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_itemO.setBackground(new java.awt.Color(255, 255, 255));
        pn_itemO.setPreferredSize(new java.awt.Dimension(222, 37));

        pn_liitemO.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_liitemOLayout = new javax.swing.GroupLayout(pn_liitemO);
        pn_liitemO.setLayout(pn_liitemOLayout);
        pn_liitemOLayout.setHorizontalGroup(
            pn_liitemOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_liitemOLayout.setVerticalGroup(
            pn_liitemOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconBaru/outgoing.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
        });

        btn_itemO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_itemO.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_itemO.setText("Item Outgoing");
        btn_itemO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_itemOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_itemOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_itemOMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_itemOLayout = new javax.swing.GroupLayout(pn_itemO);
        pn_itemO.setLayout(pn_itemOLayout);
        pn_itemOLayout.setHorizontalGroup(
            pn_itemOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_itemOLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_itemO, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_itemOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_itemOLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_liitemO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(194, Short.MAX_VALUE)))
        );
        pn_itemOLayout.setVerticalGroup(
            pn_itemOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_itemOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_itemOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_itemO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pn_itemOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_itemOLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_liitemO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_itemRe.setBackground(new java.awt.Color(255, 255, 255));
        pn_itemRe.setPreferredSize(new java.awt.Dimension(222, 37));

        pn_liitemRe.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_liitemReLayout = new javax.swing.GroupLayout(pn_liitemRe);
        pn_liitemRe.setLayout(pn_liitemReLayout);
        pn_liitemReLayout.setHorizontalGroup(
            pn_liitemReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_liitemReLayout.setVerticalGroup(
            pn_liitemReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconBaru/ireturn.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel17MouseEntered(evt);
            }
        });

        btn_itemRe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_itemRe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_itemRe.setText("Item Return");
        btn_itemRe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_itemReMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_itemReMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_itemReMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_itemReLayout = new javax.swing.GroupLayout(pn_itemRe);
        pn_itemRe.setLayout(pn_itemReLayout);
        pn_itemReLayout.setHorizontalGroup(
            pn_itemReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_itemReLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_itemRe, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(pn_itemReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_itemReLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_liitemRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(194, Short.MAX_VALUE)))
        );
        pn_itemReLayout.setVerticalGroup(
            pn_itemReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_itemReLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_itemReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_itemRe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pn_itemReLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_itemReLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_liitemRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pn_itemReq.setBackground(new java.awt.Color(255, 255, 255));
        pn_itemReq.setPreferredSize(new java.awt.Dimension(222, 37));

        pn_liitemReq.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_liitemReqLayout = new javax.swing.GroupLayout(pn_liitemReq);
        pn_liitemReq.setLayout(pn_liitemReqLayout);
        pn_liitemReqLayout.setHorizontalGroup(
            pn_liitemReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_liitemReqLayout.setVerticalGroup(
            pn_liitemReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconBaru/irequest.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
        });

        btn_itemReq.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_itemReq.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_itemReq.setText("Item Request");
        btn_itemReq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_itemReqMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_itemReqMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_itemReqMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_itemReqLayout = new javax.swing.GroupLayout(pn_itemReq);
        pn_itemReq.setLayout(pn_itemReqLayout);
        pn_itemReqLayout.setHorizontalGroup(
            pn_itemReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_itemReqLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_itemReq, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pn_itemReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_itemReqLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_liitemReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(206, Short.MAX_VALUE)))
        );
        pn_itemReqLayout.setVerticalGroup(
            pn_itemReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_itemReqLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_itemReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_itemReq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pn_itemReqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_itemReqLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pn_liitemReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("REPORT");

        pn_report.setBackground(new java.awt.Color(255, 255, 255));
        pn_report.setMaximumSize(new java.awt.Dimension(222, 37));
        pn_report.setMinimumSize(new java.awt.Dimension(222, 37));
        pn_report.setPreferredSize(new java.awt.Dimension(222, 37));

        pn_lireport.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_lireportLayout = new javax.swing.GroupLayout(pn_lireport);
        pn_lireport.setLayout(pn_lireportLayout);
        pn_lireportLayout.setHorizontalGroup(
            pn_lireportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_lireportLayout.setVerticalGroup(
            pn_lireportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconBaru/reports.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
        });

        btn_report.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_report.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_report.setText("Reports");
        btn_report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_reportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_reportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_reportMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_reportLayout = new javax.swing.GroupLayout(pn_report);
        pn_report.setLayout(pn_reportLayout);
        pn_reportLayout.setHorizontalGroup(
            pn_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_reportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_lireport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_report, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_reportLayout.setVerticalGroup(
            pn_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_reportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_reportLayout.createSequentialGroup()
                        .addComponent(pn_lireport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(pn_reportLayout.createSequentialGroup()
                        .addGroup(pn_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(3, 3, 3))))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(84, 84, 84))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(174, 174, 174)
                            .addComponent(jLabel22))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(namaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11)))))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pn_itemO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_itemIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_itemB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_itemReq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pn_itemRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(namaKaryawan)
                .addGap(70, 70, 70)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_itemB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_itemIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_itemO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_itemRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_itemReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_report, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(41, 76, 55));
        kGradientPanel1.setkGradientFocus(750);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1070, 55));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconBaru/logo.png"))); // NOI18N
        jLabel1.setText("Inventhera");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(865, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.add(kGradientPanel1, java.awt.BorderLayout.PAGE_START);

        kGradientPanel2.setkEndColor(new java.awt.Color(41, 76, 55));
        kGradientPanel2.setkGradientFocus(750);
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 153, 153));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(1070, 17));

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );

        jPanel3.add(kGradientPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setMaximumSize(new java.awt.Dimension(910, 600));
        pn_utama.setMinimumSize(new java.awt.Dimension(910, 600));
        pn_utama.setPreferredSize(new java.awt.Dimension(910, 600));
        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseEntered

    private void btn_itemBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemBMouseClicked
        pn_itemB.setBackground(new Color(240, 240, 240));
        pn_liitemB.setBackground(new Color(0, 102, 102));

        pn_utama.removeAll();
        pn_utama.add(new transaksi.peminjaman_Barang());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_itemBMouseClicked

    private void btn_itemBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemBMouseEntered
        pn_itemB.setBackground(new Color(250, 250, 250));
        pn_liitemB.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btn_itemBMouseEntered

    private void btn_itemBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemBMouseExited
        pn_itemB.setBackground(new Color(255, 255, 255));
        pn_liitemB.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_itemBMouseExited

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseEntered

    private void btn_itemInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemInMouseClicked
        pn_itemIn.setBackground(new Color(240, 240, 240));
        pn_liitemIn.setBackground(new Color(0, 102, 102));

        pn_utama.removeAll();
        pn_utama.add(new transaksi.barang_masuk());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_itemInMouseClicked

    private void btn_itemInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemInMouseEntered
        pn_itemIn.setBackground(new Color(250, 250, 250));
        pn_liitemIn.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btn_itemInMouseEntered

    private void btn_itemInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemInMouseExited
        pn_itemIn.setBackground(new Color(255, 255, 255));
        pn_liitemIn.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_itemInMouseExited

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseEntered

    private void btn_itemOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemOMouseClicked
        pn_itemO.setBackground(new Color(240, 240, 240));
        pn_liitemO.setBackground(new Color(0, 102, 102));

        pn_utama.removeAll();
        pn_utama.add(new transaksi.barang_keluar());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_itemOMouseClicked

    private void btn_itemOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemOMouseEntered
        pn_itemO.setBackground(new Color(250, 250, 250));
        pn_liitemO.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btn_itemOMouseEntered

    private void btn_itemOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemOMouseExited
        pn_itemO.setBackground(new Color(255, 255, 255));
        pn_liitemO.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_itemOMouseExited

    private void jLabel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseEntered

    private void btn_itemReMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemReMouseClicked
        pn_itemRe.setBackground(new Color(240, 240, 240));
        pn_liitemRe.setBackground(new Color(0, 102, 102));

        pn_utama.removeAll();
        pn_utama.add(new transaksi.pengembalian_Barang());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_itemReMouseClicked

    private void btn_itemReMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemReMouseEntered
        pn_itemRe.setBackground(new Color(250, 250, 250));
        pn_liitemRe.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btn_itemReMouseEntered

    private void btn_itemReMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemReMouseExited
        pn_itemRe.setBackground(new Color(255, 255, 255));
        pn_liitemRe.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_itemReMouseExited

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseEntered

    private void btn_itemReqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemReqMouseClicked
        pn_itemReq.setBackground(new Color(240, 240, 240));
        pn_liitemReq.setBackground(new Color(0, 102, 102));

        pn_utama.removeAll();
        pn_utama.add(new transaksi.permintaan_Barang());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_itemReqMouseClicked

    private void btn_itemReqMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemReqMouseEntered
        pn_itemReq.setBackground(new Color(250, 250, 250));
        pn_liitemReq.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btn_itemReqMouseEntered

    private void btn_itemReqMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemReqMouseExited
        pn_itemReq.setBackground(new Color(255, 255, 255));
        pn_liitemReq.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_itemReqMouseExited

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseEntered

    private void btn_reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportMouseClicked
        pn_report.setBackground(new Color(240, 240, 240));
        pn_lireport.setBackground(new Color(0, 102, 102));

        pn_utama.removeAll();
        pn_utama.add(new menuReport.menu_report());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_reportMouseClicked

    private void btn_reportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportMouseEntered
        pn_report.setBackground(new Color(250, 250, 250));
        pn_lireport.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_btn_reportMouseEntered

    private void btn_reportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportMouseExited
        pn_report.setBackground(new Color(255, 255, 255));
        pn_lireport.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_reportMouseExited

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        this.dispose();
        new tampilanMenu.loginPage().setVisible(true);
    }//GEN-LAST:event_jLabel22MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_inventaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_inventaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_inventaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_inventaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_inventaris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_itemB;
    private javax.swing.JLabel btn_itemIn;
    private javax.swing.JLabel btn_itemO;
    private javax.swing.JLabel btn_itemRe;
    private javax.swing.JLabel btn_itemReq;
    private javax.swing.JLabel btn_report;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel namaKaryawan;
    private javax.swing.JPanel pn_itemB;
    private javax.swing.JPanel pn_itemIn;
    private javax.swing.JPanel pn_itemO;
    private javax.swing.JPanel pn_itemRe;
    private javax.swing.JPanel pn_itemReq;
    private javax.swing.JPanel pn_liitemB;
    private javax.swing.JPanel pn_liitemIn;
    private javax.swing.JPanel pn_liitemO;
    private javax.swing.JPanel pn_liitemRe;
    private javax.swing.JPanel pn_liitemReq;
    private javax.swing.JPanel pn_lireport;
    private javax.swing.JPanel pn_report;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
