/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilanMenu;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ALKHOIR
 */
public class menuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form menuFinal
     */
    
    private String hakAkses;
    private String idKaryawan;
    private String namaKaryawan;
    
    public menuAdmin() {
        initComponents();
        setTitle("Inventaris Perkantoran");
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/logof.png"));
        setIconImage(icon.getImage());
        
        hakAkses = loginSesi.getHakAkses();
        idKaryawan = loginSesi.getIdKaryawan();
        namaKaryawan = loginSesi.getNamaKaryawan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        bDataAkun = new javax.swing.JButton();
        bDataDivisi = new javax.swing.JButton();
        bDataKaryawan = new javax.swing.JButton();
        bStokBarangInfo = new javax.swing.JButton();
        bDataBarang = new javax.swing.JButton();
        bDataPengembalianBarang = new javax.swing.JButton();
        dataPengembalianInfo = new javax.swing.JButton();
        bStokBarang = new javax.swing.JButton();
        bDataJabatan = new javax.swing.JButton();
        bDataTransaksi = new javax.swing.JButton();
        bDataTransaksiInfo = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        dataAkun = new javax.swing.JMenuItem();
        dataDivisi = new javax.swing.JMenuItem();
        dataKaryawan = new javax.swing.JMenuItem();
        stokBarangInfo = new javax.swing.JMenuItem();
        dataBarang = new javax.swing.JMenuItem();
        dataPengembalianBarang = new javax.swing.JMenuItem();
        stokBarang = new javax.swing.JMenuItem();
        dataJabatan = new javax.swing.JMenuItem();
        dataTransaksi = new javax.swing.JMenuItem();
        dataTransaksiInfo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        peminjamanBarang = new javax.swing.JMenuItem();
        barangMasuk = new javax.swing.JMenuItem();
        barangKeluar = new javax.swing.JMenuItem();
        pengembalianBarang = new javax.swing.JMenuItem();
        permintaanBarang = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 550));
        setResizable(false);

        kGradientPanel1.setBackground(new java.awt.Color(41, 76, 55));
        kGradientPanel1.setkEndColor(new java.awt.Color(41, 76, 55));
        kGradientPanel1.setkGradientFocus(250);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setMaximumSize(new java.awt.Dimension(680, 583));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(680, 583));

        bDataAkun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/acc.png"))); // NOI18N
        bDataAkun.setText("Account Data");
        bDataAkun.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55)));
        bDataAkun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDataAkun.setMaximumSize(new java.awt.Dimension(200, 100));
        bDataAkun.setMinimumSize(new java.awt.Dimension(200, 100));
        bDataAkun.setPreferredSize(new java.awt.Dimension(200, 100));
        bDataAkun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bDataAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataAkunActionPerformed(evt);
            }
        });

        bDataDivisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/division.png"))); // NOI18N
        bDataDivisi.setText("Division Data");
        bDataDivisi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55)));
        bDataDivisi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDataDivisi.setMaximumSize(new java.awt.Dimension(200, 100));
        bDataDivisi.setMinimumSize(new java.awt.Dimension(200, 100));
        bDataDivisi.setPreferredSize(new java.awt.Dimension(200, 100));
        bDataDivisi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bDataDivisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataDivisiActionPerformed(evt);
            }
        });

        bDataKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/employee.png"))); // NOI18N
        bDataKaryawan.setText("Employee Data");
        bDataKaryawan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55)));
        bDataKaryawan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDataKaryawan.setMaximumSize(new java.awt.Dimension(200, 100));
        bDataKaryawan.setMinimumSize(new java.awt.Dimension(200, 100));
        bDataKaryawan.setPreferredSize(new java.awt.Dimension(200, 100));
        bDataKaryawan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bDataKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataKaryawanActionPerformed(evt);
            }
        });

        bStokBarangInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/invendetails.png"))); // NOI18N
        bStokBarangInfo.setText("Inventory Details");
        bStokBarangInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55)));
        bStokBarangInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bStokBarangInfo.setMaximumSize(new java.awt.Dimension(200, 100));
        bStokBarangInfo.setMinimumSize(new java.awt.Dimension(200, 100));
        bStokBarangInfo.setPreferredSize(new java.awt.Dimension(200, 100));
        bStokBarangInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bStokBarangInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStokBarangInfoActionPerformed(evt);
            }
        });

        bDataBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/item.png"))); // NOI18N
        bDataBarang.setText("Item Data");
        bDataBarang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55)));
        bDataBarang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDataBarang.setMaximumSize(new java.awt.Dimension(200, 100));
        bDataBarang.setMinimumSize(new java.awt.Dimension(200, 100));
        bDataBarang.setPreferredSize(new java.awt.Dimension(200, 100));
        bDataBarang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataBarangActionPerformed(evt);
            }
        });

        bDataPengembalianBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/return.png"))); // NOI18N
        bDataPengembalianBarang.setText("Item Return Data");
        bDataPengembalianBarang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55)));
        bDataPengembalianBarang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDataPengembalianBarang.setMaximumSize(new java.awt.Dimension(200, 100));
        bDataPengembalianBarang.setMinimumSize(new java.awt.Dimension(200, 100));
        bDataPengembalianBarang.setPreferredSize(new java.awt.Dimension(200, 100));
        bDataPengembalianBarang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bDataPengembalianBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataPengembalianBarangActionPerformed(evt);
            }
        });

        dataPengembalianInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/returninfo.png"))); // NOI18N
        dataPengembalianInfo.setText("Item Return Info");
        dataPengembalianInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55)));
        dataPengembalianInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dataPengembalianInfo.setMaximumSize(new java.awt.Dimension(200, 100));
        dataPengembalianInfo.setMinimumSize(new java.awt.Dimension(200, 100));
        dataPengembalianInfo.setPreferredSize(new java.awt.Dimension(200, 100));
        dataPengembalianInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dataPengembalianInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataPengembalianInfoActionPerformed(evt);
            }
        });

        bStokBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/stockinven.png"))); // NOI18N
        bStokBarang.setText("Stock Inventory");
        bStokBarang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55)));
        bStokBarang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bStokBarang.setMaximumSize(new java.awt.Dimension(200, 100));
        bStokBarang.setMinimumSize(new java.awt.Dimension(200, 100));
        bStokBarang.setPreferredSize(new java.awt.Dimension(200, 100));
        bStokBarang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bStokBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStokBarangActionPerformed(evt);
            }
        });

        bDataJabatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/position.png"))); // NOI18N
        bDataJabatan.setText("Position Data");
        bDataJabatan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55)));
        bDataJabatan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDataJabatan.setMaximumSize(new java.awt.Dimension(200, 100));
        bDataJabatan.setMinimumSize(new java.awt.Dimension(200, 100));
        bDataJabatan.setPreferredSize(new java.awt.Dimension(200, 100));
        bDataJabatan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bDataJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataJabatanActionPerformed(evt);
            }
        });

        bDataTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transaction.png"))); // NOI18N
        bDataTransaksi.setText("Transaction Data");
        bDataTransaksi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55)));
        bDataTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDataTransaksi.setMaximumSize(new java.awt.Dimension(200, 100));
        bDataTransaksi.setMinimumSize(new java.awt.Dimension(200, 100));
        bDataTransaksi.setPreferredSize(new java.awt.Dimension(200, 100));
        bDataTransaksi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bDataTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataTransaksiActionPerformed(evt);
            }
        });

        bDataTransaksiInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transactioninfo.png"))); // NOI18N
        bDataTransaksiInfo.setText("Transaction Info");
        bDataTransaksiInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55), new java.awt.Color(41, 76, 55)));
        bDataTransaksiInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDataTransaksiInfo.setMaximumSize(new java.awt.Dimension(200, 100));
        bDataTransaksiInfo.setMinimumSize(new java.awt.Dimension(200, 100));
        bDataTransaksiInfo.setPreferredSize(new java.awt.Dimension(200, 100));
        bDataTransaksiInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bDataTransaksiInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDataTransaksiInfoActionPerformed(evt);
            }
        });

        jButton28.setBackground(new java.awt.Color(41, 76, 55));
        jButton28.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jButton28.setForeground(new java.awt.Color(255, 255, 255));
        jButton28.setText("EXIT");
        jButton28.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(bStokBarangInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bDataBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bDataPengembalianBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(bDataAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bDataDivisi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bDataKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(dataPengembalianInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bStokBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bDataJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(bDataTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bDataTransaksiInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDataAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDataDivisi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDataKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bStokBarangInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDataBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDataPengembalianBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataPengembalianInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bStokBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDataJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDataTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDataTransaksiInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenu1.setText("Master");

        dataAkun.setText("Account Data");
        dataAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataAkunActionPerformed(evt);
            }
        });
        jMenu1.add(dataAkun);

        dataDivisi.setText("Division Data");
        dataDivisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDivisiActionPerformed(evt);
            }
        });
        jMenu1.add(dataDivisi);

        dataKaryawan.setText("Employee Data");
        dataKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataKaryawanActionPerformed(evt);
            }
        });
        jMenu1.add(dataKaryawan);

        stokBarangInfo.setText("Inventory Details");
        stokBarangInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokBarangInfoActionPerformed(evt);
            }
        });
        jMenu1.add(stokBarangInfo);

        dataBarang.setText("Item Data");
        dataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataBarangActionPerformed(evt);
            }
        });
        jMenu1.add(dataBarang);

        dataPengembalianBarang.setText("Item Return Data");
        dataPengembalianBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataPengembalianBarangActionPerformed(evt);
            }
        });
        jMenu1.add(dataPengembalianBarang);

        stokBarang.setText("Stock Inventory");
        stokBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokBarangActionPerformed(evt);
            }
        });
        jMenu1.add(stokBarang);

        dataJabatan.setText("Position Data");
        dataJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataJabatanActionPerformed(evt);
            }
        });
        jMenu1.add(dataJabatan);

        dataTransaksi.setText("Transaction Data");
        dataTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataTransaksiActionPerformed(evt);
            }
        });
        jMenu1.add(dataTransaksi);

        dataTransaksiInfo.setText("Transaction Info");
        dataTransaksiInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataTransaksiInfoActionPerformed(evt);
            }
        });
        jMenu1.add(dataTransaksiInfo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        peminjamanBarang.setText("Item Borrowing");
        peminjamanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjamanBarangActionPerformed(evt);
            }
        });
        jMenu2.add(peminjamanBarang);

        barangMasuk.setText("Item Incoming");
        barangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangMasukActionPerformed(evt);
            }
        });
        jMenu2.add(barangMasuk);

        barangKeluar.setText("Item Outgoing");
        barangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangKeluarActionPerformed(evt);
            }
        });
        jMenu2.add(barangKeluar);

        pengembalianBarang.setText("Item Return");
        pengembalianBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalianBarangActionPerformed(evt);
            }
        });
        jMenu2.add(pengembalianBarang);

        permintaanBarang.setText("Item Request");
        permintaanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permintaanBarangActionPerformed(evt);
            }
        });
        jMenu2.add(permintaanBarang);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dataDivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDivisiActionPerformed
        this.dispose();
        new Master.dataDivisi().setVisible(true);
    }//GEN-LAST:event_dataDivisiActionPerformed

    private void dataKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataKaryawanActionPerformed
        this.dispose();
        new Master.dataKaryawan().setVisible(true);
    }//GEN-LAST:event_dataKaryawanActionPerformed

    private void dataAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataAkunActionPerformed
        this.dispose();
        new Master.dataAkun().setVisible(true);
    }//GEN-LAST:event_dataAkunActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog (
            this,
            "Apakah Anda yakin ingin keluar?",
            "Konfirmasi Keluar",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton28ActionPerformed

    private void dataPengembalianInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataPengembalianInfoActionPerformed
        this.dispose();
        new Master.dataPengembalianInfo().setVisible(true);
    }//GEN-LAST:event_dataPengembalianInfoActionPerformed

    private void bStokBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStokBarangActionPerformed
        this.dispose();
        new Master.stokBarang().setVisible(true);
    }//GEN-LAST:event_bStokBarangActionPerformed

    private void bDataPengembalianBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataPengembalianBarangActionPerformed
        this.dispose();
        new Master.dataPengembalianBarang().setVisible(true);
    }//GEN-LAST:event_bDataPengembalianBarangActionPerformed

    private void bStokBarangInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStokBarangInfoActionPerformed
        this.dispose();
        new Master.stokBarang().setVisible(true);
    }//GEN-LAST:event_bStokBarangInfoActionPerformed

    private void bDataAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataAkunActionPerformed
        this.dispose();
        new Master.dataAkun().setVisible(true);
    }//GEN-LAST:event_bDataAkunActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void permintaanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permintaanBarangActionPerformed
        this.dispose();
        new transaksi.permintaanBarang().setVisible(true);
    }//GEN-LAST:event_permintaanBarangActionPerformed

    private void stokBarangInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokBarangInfoActionPerformed
        this.dispose();
        new Master.stokBarangInfo().setVisible(true);
    }//GEN-LAST:event_stokBarangInfoActionPerformed

    private void dataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataBarangActionPerformed
        this.dispose();
        new Master.dataBarang().setVisible(true);
    }//GEN-LAST:event_dataBarangActionPerformed

    private void dataPengembalianBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataPengembalianBarangActionPerformed
        this.dispose();
        new Master.dataPengembalianBarang().setVisible(true);
    }//GEN-LAST:event_dataPengembalianBarangActionPerformed

    private void stokBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stokBarangActionPerformed
        this.dispose();
        new Master.stokBarang().setVisible(true);
    }//GEN-LAST:event_stokBarangActionPerformed

    private void dataJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataJabatanActionPerformed
        this.dispose();
        new Master.dataJabatan().setVisible(true);
    }//GEN-LAST:event_dataJabatanActionPerformed

    private void dataTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataTransaksiActionPerformed
        this.dispose();
        new Master.dataTransaksi().setVisible(true);
    }//GEN-LAST:event_dataTransaksiActionPerformed

    private void dataTransaksiInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataTransaksiInfoActionPerformed
        this.dispose();
        new Master.dataTransaksiInfo().setVisible(true);
    }//GEN-LAST:event_dataTransaksiInfoActionPerformed

    private void peminjamanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjamanBarangActionPerformed
        this.dispose();
        new transaksi.peminjamanBarang().setVisible(true);
    }//GEN-LAST:event_peminjamanBarangActionPerformed

    private void barangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangMasukActionPerformed
        this.dispose();
        new transaksi.barangMasuk().setVisible(true);
    }//GEN-LAST:event_barangMasukActionPerformed

    private void barangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangKeluarActionPerformed
        this.dispose();
        new transaksi.barangKeluar().setVisible(true);
    }//GEN-LAST:event_barangKeluarActionPerformed

    private void pengembalianBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalianBarangActionPerformed
        this.dispose();
        new transaksi.pengembalianBarang().setVisible(true);
    }//GEN-LAST:event_pengembalianBarangActionPerformed

    private void bDataDivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataDivisiActionPerformed
        this.dispose();
        new Master.dataDivisi().setVisible(true);
    }//GEN-LAST:event_bDataDivisiActionPerformed

    private void bDataKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataKaryawanActionPerformed
        this.dispose();
        new Master.dataKaryawan().setVisible(true);
    }//GEN-LAST:event_bDataKaryawanActionPerformed

    private void bDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataBarangActionPerformed
        this.dispose();
        new Master.dataBarang().setVisible(true);
    }//GEN-LAST:event_bDataBarangActionPerformed

    private void bDataJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataJabatanActionPerformed
        this.dispose();
        new Master.dataJabatan().setVisible(true);
    }//GEN-LAST:event_bDataJabatanActionPerformed

    private void bDataTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataTransaksiActionPerformed
        this.dispose();
        new Master.dataTransaksi().setVisible(true);
    }//GEN-LAST:event_bDataTransaksiActionPerformed

    private void bDataTransaksiInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDataTransaksiInfoActionPerformed
        this.dispose();
        new Master.dataTransaksiInfo().setVisible(true);
    }//GEN-LAST:event_bDataTransaksiInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDataAkun;
    private javax.swing.JButton bDataBarang;
    private javax.swing.JButton bDataDivisi;
    private javax.swing.JButton bDataJabatan;
    private javax.swing.JButton bDataKaryawan;
    private javax.swing.JButton bDataPengembalianBarang;
    private javax.swing.JButton bDataTransaksi;
    private javax.swing.JButton bDataTransaksiInfo;
    private javax.swing.JButton bStokBarang;
    private javax.swing.JButton bStokBarangInfo;
    private javax.swing.JMenuItem barangKeluar;
    private javax.swing.JMenuItem barangMasuk;
    private javax.swing.JMenuItem dataAkun;
    private javax.swing.JMenuItem dataBarang;
    private javax.swing.JMenuItem dataDivisi;
    private javax.swing.JMenuItem dataJabatan;
    private javax.swing.JMenuItem dataKaryawan;
    private javax.swing.JMenuItem dataPengembalianBarang;
    private javax.swing.JButton dataPengembalianInfo;
    private javax.swing.JMenuItem dataTransaksi;
    private javax.swing.JMenuItem dataTransaksiInfo;
    private javax.swing.JButton jButton28;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JMenuItem peminjamanBarang;
    private javax.swing.JMenuItem pengembalianBarang;
    private javax.swing.JMenuItem permintaanBarang;
    private javax.swing.JMenuItem stokBarang;
    private javax.swing.JMenuItem stokBarangInfo;
    // End of variables declaration//GEN-END:variables
}
